ansible_network_os: ios
ansible_connection: network_cli
ansible_user: lab
ansible_password: lab123
ansible_become: yes
ansible_become_password: admin123
ansible_become_method: enable

name_servers: 10.1.106.1
ntp_server: 10.1.106.1
domain_name: ansible.com