stages:
  - build
  - run

build:
  stage: build
  script: 
    - rm -f -R b2b-network-automation
    - git clone git@gitlab.b2b.ole-lab.com:waleed/b2b-network-automation.git
    - cd b2b-network-automation/
    - chmod +x ansble.sh

run:
  stage: run
  script:
    - bash ./ansible.sh
